### ISSUE TITLE
Alt + 2 can crash race 

### ISSUE THREAD

**Issue by rexsilex** [DU-Racing/DU-Racing-System#21]
**Describe the bug**
Clicking Alt + 2 (usually because it does something else on your script) crashes the game while running the vehicle install midrace.

**Comment by D4DG** [comment]
@rexsilex Could you give some more detail on this.
I checked the code and see no reason for this to happen.

The only thing that should happen when pressing "f2" while in a normal or a test race is creating a errorprintout to the console stating: "You can only save waypoints in orgMode."
